config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  # TODO auth security https://thoughtbot.com/blog/rails-advanced-routing-constraints
  mount Sidekiq::Web => "/sidekiq"

  namespace :admin do
    root "home#index"

    resources :categories, except: :show
    resources :courses, except: %i[new create]
    resources :roles, shallow: true do
      resources :permissions, only: %i[create update] do
        patch :toggle, on: :member # move to toggle controller
      end
    end

    resources :documents, shallow: true, except: %i[new create] do
      resources :paragraphs, except: %i[index show]
    end

    resources :posts, except: %i[new create]
    resources :decks, except: %i[new create]
  end

  namespace :dashboard do
    root "home#index"

    resources :documents do
      resources :paragraphs, shallow: true, except: %i[index show]
    end

    resources :courses do
      resources :chapters, shallow: true, except: %i[index show]
    end

    resources :decks do
      resources :cards, shallow: true, except: %i[index show]
    end

    resources :class_rooms
    resources :posts
  end

  resources :categories, only: %i[index show]
  resources :posts, only: %i[index show]

  resource :registration, only: %i[new create]
  resource :session, only: %i[new create destroy]
  resource :password, only: %i[edit update]
  resource :remind_password, only: %i[new create]
  resource :reset_password, only: %i[edit update]

  get "main", to: "pages#main"
  get "about_us", to: "pages#about_us"
  get "terms_of_service", to: "pages#terms_of_service"
  get "services", to: "pages#services"

  get "up", to: "rails/health#show", as: :rails_health_check

  root "pages#main"
end

app/views/shared/_footer.html.haml
%footer.bg-gray-50.w-full
  .mx-auto.px-5.py-5
    %ul.flex.flex-wrap.justify-between.max-w-screen-md.mx-auto
      %li
        = link_to 'About us', about_us_path,
                  class: 'text-gray-600 hover:text-gray-800 transition-colors duration-300'
      %li
        = link_to 'Services', services_path,
                  class: 'text-gray-600 hover:text-gray-800 transition-colors duration-300'

app/views/shared/_header.html.haml
%header.bg-gray-50.w-full
  %nav.mx-auto.px-5.py-5
    .flex.justify-between
      %h5
        = link_to 'Grammarats', root_path,
                  class: 'font-bold text-gray-600 hover:text-gray-800 transition-colors duration-300'
      .block
        %ul.flex.items-center.space-x-8
          - if user_signed_in?
            %li
              = link_to 'Class rooms', dashboard_class_rooms_path,
                        class: 'text-gray-600 hover:text-gray-800 transition-colors duration-300'
            %li
              = link_to 'Courses', dashboard_courses_path,
                        class: 'text-gray-600 hover:text-gray-800 transition-colors duration-300'
            %li
              = link_to 'Documents', dashboard_documents_path,
                        class: 'text-gray-600 hover:text-gray-800 transition-colors duration-300'
            %li
              = link_to 'Edit password', edit_password_path,
                        class: 'text-gray-600 hover:text-gray-800 transition-colors duration-300'

            %li
              = button_to 'Log out', session_path, method: :delete,
                          class: 'text-gray-600 hover:text-gray-800 transition-colors duration-300'

          - else
            %li
              = link_to 'About us', about_us_path,
                        class: 'text-gray-600 hover:text-gray-800 transition-colors duration-300'
            %li
              = link_to 'Services', services_path,
                        class: 'text-gray-600 hover:text-gray-800 transition-colors duration-300'
            %li
              = link_to 'Log In', new_session_path,
                        class: 'text-gray-600 hover:text-gray-800 transition-colors duration-300'
            %li
              = link_to 'Sign Up', new_registration_path,
                        class: 'text-gray-600 hover:text-gray-800 transition-colors duration-300'