config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  # TODO auth security https://thoughtbot.com/blog/rails-advanced-routing-constraints
  mount Sidekiq::Web => "/sidekiq"

  namespace :admin do
    root "home#index"

    resources :categories, except: :show
    resources :courses, except: %i[new create]
    resources :roles, shallow: true do
      resources :permissions, only: %i[create update] do
        patch :toggle, on: :member # move to toggle controller
      end
    end

    resources :documents, shallow: true, except: %i[new create] do
      resources :paragraphs, except: %i[index show]
    end

    resources :posts, except: %i[new create]
    resources :decks, except: %i[new create]
  end

  namespace :dashboard do
    root "home#index"

    resources :documents do
      resources :paragraphs, shallow: true, except: %i[index show]
    end

    resources :courses do
      resources :chapters, shallow: true, except: %i[index show]
    end

    resources :decks do
      resources :cards, shallow: true, except: %i[index show]
    end

    resources :class_rooms
    resources :posts
  end

  resources :categories, only: %i[index show]
  resources :posts, only: %i[index show]

  resource :registration, only: %i[new create]
  resource :session, only: %i[new create destroy]
  resource :password, only: %i[edit update]
  resource :remind_password, only: %i[new create]
  resource :reset_password, only: %i[edit update]

  get "main", to: "pages#main"
  get "about_us", to: "pages#about_us"
  get "terms_of_service", to: "pages#terms_of_service"
  get "services", to: "pages#services"

  get "up", to: "rails/health#show", as: :rails_health_check

  root "pages#main"
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  include RoleRepository
  include RoleStateMachine

  NAME = { min: 2, max: 255 }.freeze
  DESCRIPTION = { max: 16_384 }.freeze

  has_many :permissions, dependent: :destroy

  validates :name, presence: true,
                   length: { in: NAME[:min]..NAME[:max] },
                   uniqueness: { case_sensitive: false }

  validates :description, length: { maximum: DESCRIPTION[:max] }
  validates :state, presence: true, inclusion: { in: %w[pending archived activated] }

  normalizes :description, with: ->(description) { description.strip.capitalize }
  normalizes :name, with: ->(name) { name.strip.capitalize }

  def self.ransackable_attributes(_auth_object = nil)
    %w[activated_at archived_at created_at description name]
  end
end

app/controllers/admin/roles_controller.rb
# frozen_string_literal: true

module Admin
  class RolesController < Admin::ApplicationController
    before_action :load_role, only: %i[show edit update destroy]

    def index
      @query = Role.ransack(params[:query])
      @roles = @query.result(distinct: true)
    end

    def show
      @permissions = @role.permission_data
    end

    def new
      @role = Role.new
    end

    def edit; end

    def create
      @role = Role.new(role_params)

      if @role.save
        redirect_to(admin_roles_path,
                    success: t("common.create.success", model_name:))
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @role.update(role_params)
        redirect_to(admin_roles_path,
                    success: t("common.update.success", model_name:))
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      delete_service = ::Roles::DeleteService.call(role: @role)

      if delete_service.success
        redirect_to(admin_roles_path,
                    status: :see_other,
                    notice: t("common.destroy.notice", model_name:))
      else
        redirect_to(admin_roles_path, alert: delete_service.failure)
      end
    end

    private

    def load_role
      @role = Role.find(params[:id])
    end

    def role_params
      params.require(:role).permit(:name, :description)
    end
  end
end

app/views/admin/roles/_form.html.haml
= form_with(model: [:admin, @role], class: 'max-w-2xl mx-auto') do |form|
  - if form.object.errors.any?
    - form.object.errors.full_messages.each do |message|
      %div= message

  .my-4
    %label= form.label :name, class: 'block mb-2 text-gray-600 text-sm tracking-wide'
    = form.text_field :name,
                      class: 'bg-gray-50 border-gray-300 text-gray-800 block w-full p-2 focus:border-indigo-700'

  .my-4
    %label= form.label :description, class: 'block mb-2 text-gray-600 text-sm tracking-wide'
    = form.text_area :description,
                     class: 'bg-gray-50 border-gray-300 text-gray-800 block w-full p-2 focus:border-indigo-700'

  .grid.grid-cols-2.gap-2
    %div
      = form.submit(@role.new_record? ? 'Save' : 'Update',
                    class: 'block text-gray-50 bg-indigo-500 hover:bg-indigo-800 w-full p-2 transition-colors duration-300 text-center tracking-wide')

    %div
      = link_to 'Back', admin_roles_path,
                class: 'block text-gray-50 bg-gray-500 hover:bg-gray-800 w-full p-2 transition-colors duration-300 text-center tracking-wide'

app/views/admin/roles/_role.html.haml
= tag.tr id: dom_id(role), class: 'hover:bg-gray-50 border-b border-gray-300 text-gray-600' do
  %td.p-5= role.name
  %td.p-5= role.state
  %td.p-5= role.activated_at
  %td.p-5= role.archived_at
  %td.p-5
    .flex.justify-center
      = link_to heroicon('pencil',
                         options: { class: 'mr-2 text-indigo-500 hover:text-indigo-800 transition-colors duration-300' }),
                edit_admin_role_path(role),
                data: { turbo_frame: '_top' }
      = link_to heroicon('trash',
                         options: { class: 'text-red-500 hover:text-red-800 transition-colors duration-300' }),
                admin_role_path(role),
                data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }

app/views/admin/roles/edit.html.haml
= provide :page_title, 'Edit role'

= render 'form'

app/views/admin/roles/index.html.haml
= provide :page_title, 'Roles'

.grid.grid-cols-15_85.h-full
  = render 'admin/shared/aside'

  .m-10
    %nav.mb-10
      %ul.flex.md:flex-row.justify-between
        %li
          = link_to 'New Role', new_admin_role_path,
                    class: 'block text-gray-50 bg-indigo-500 hover:bg-indigo-800 p-2 transition-colors duration-300 text-center tracking-wide'

        %li
          = search_form_for([:admin, @query], html: { 'data-turbo-frame': 'roles' }) do |form|
            = form.search_field :name_i_cont,
                                placeholder: 'Searching by name',
                                class: 'bg-gray-50 border-gray-300 text-gray-800 p-2 focus:border-indigo-700'
            = form.submit(class: 'text-gray-50 bg-indigo-500 hover:bg-indigo-800 p-2 transition-colors duration-300 text-center tracking-wide')


    %section
      = turbo_frame_tag 'roles' do
        %p.content-loading TODO: Table skeleton

        %table.border-collapse.w-full.leading-normal
          %thead.uppercase.border-b.border-indigo-500
            %tr
              %th.px-5.py-3.text-indigo-800.text-left= sort_link(@query, :title, 'Title')
              %th.px-5.py-3.text-indigo-800.text-left= sort_link(@query, :state, 'State')
              %th.px-5.py-3.text-indigo-800.text-left= sort_link(@query, :activated_at, 'Activated at')
              %th.px-5.py-3.text-indigo-800.text-left= sort_link(@query, :archived_at, 'Archived at')
              %th.px-5.py-3.text-indigo-800 Actions
          %tbody
            = render @roles

app/views/admin/roles/new.html.haml
= provide :page_title, 'New role'

= render 'form'

app/views/admin/roles/show.html.haml
= provide :page_title, @role.name

- if @permissions.empty?
  = button_to 'Create permissions', admin_role_permissions_path(@role), method: :create
- else
  = button_to 'Check new permissions', admin_role_permissions_path(@role), method: :put

- @permissions.each do |permission|
  %h3= permission[:model]
  = check_box_tag permission[:verb], {}