config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  # TODO auth security https://thoughtbot.com/blog/rails-advanced-routing-constraints
  mount Sidekiq::Web => "/sidekiq"

  namespace :admin do
    root "home#index"

    resources :categories, except: :show
    resources :courses, except: %i[new create]
    resources :roles, shallow: true do
      resources :permissions, only: %i[create update] do
        patch :toggle, on: :member # move to toggle controller
      end
    end

    resources :documents, shallow: true, except: %i[new create] do
      resources :paragraphs, except: %i[index show]
    end

    resources :posts, except: %i[new create]
    resources :decks, except: %i[new create]
  end

  namespace :dashboard do
    root "home#index"

    resources :documents do
      resources :paragraphs, shallow: true, except: %i[index show]
    end

    resources :courses do
      resources :chapters, shallow: true, except: %i[index show]
    end

    resources :decks do
      resources :cards, shallow: true, except: %i[index show]
    end

    resources :class_rooms
    resources :posts
  end

  resources :categories, only: %i[index show]
  resources :posts, only: %i[index show]

  resource :registration, only: %i[new create]
  resource :session, only: %i[new create destroy]
  resource :password, only: %i[edit update]
  resource :remind_password, only: %i[new create]
  resource :reset_password, only: %i[edit update]

  get "main", to: "pages#main"
  get "about_us", to: "pages#about_us"
  get "terms_of_service", to: "pages#terms_of_service"
  get "services", to: "pages#services"

  get "up", to: "rails/health#show", as: :rails_health_check

  root "pages#main"
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  include CategoryRepository
  include CategoryStateMachine

  TITLE = { min: 2, max: 255 }.freeze
  DESCRIPTION = { max: 16_384 }.freeze
  SLUG = { min: 2, max: 300 }.freeze

  has_many :posts

  before_validation :set_slug

  validates :title, presence: true,
                    length: { in: TITLE[:min]..TITLE[:max] },
                    uniqueness: { case_sensitive: false }

  validates :description, length: { maximum: DESCRIPTION[:max] }
  validates :state, presence: true, inclusion: { in: %w[activated archived] }
  validates :slug, presence: true, length: { in: SLUG[:min]..SLUG[:max] }

  normalizes :description, with: ->(description) { description.strip.capitalize }
  normalizes :slug, with: ->(slug) { slug.strip.parameterize }
  normalizes :title, with: ->(title) { title.strip.capitalize }

  attribute :posts_count, default: 0

  def self.ransackable_attributes(_auth_object = nil)
    %w[archived_at created_at posts_count slug state title]
  end

  def self.ransackable_associations(_auth_object = nil) = [ "posts" ]

  private

  def set_slug
    self.slug = title&.strip&.parameterize
  end
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

module Admin
  class CategoriesController < Admin::ApplicationController
    before_action :load_category, only: %i[edit update destroy]

    def index
      @query = Category.ransack(params[:query])
      @categories = @query.result(distinct: true)
    end

    def new
      @category = Category.new
    end

    def edit; end

    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to(admin_categories_path,
                    success: t("common.create.success", model_name:))
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      update_service = ::Categories::UpdateService.call(category: @category, category_params:)

      if update_service.success?
        redirect_to(admin_categories_path,
                    success: t("common.update.success", model_name:))
      else
        render :edit, status: :unprocessable_entity
        # flash update_service.failure
      end
    end

    def destroy
      delete_service = ::Categories::DeleteService.call(category: @category)

      if delete_service.success?
        redirect_to(admin_categories_path,
                    status: :see_other,
                    notice: t("common.destroy.notice", model_name:))
      else
        redirect_to(admin_categories_path, alert: delete_service.failure)
      end
    end

    private

    def load_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:title, :description)
    end
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :load_category, only: :show

  def index
    @categories = Category.activated
  end

  def show; end

  private

  def load_category
    @category = Category.find(params[:id])
  end
end

app/views/admin/categories/_category.html.haml
= tag.tr id: dom_id(category), class: 'hover:bg-gray-50 border-b border-gray-300 text-gray-600' do
  %td.p-5= category.title
  %td.p-5= category.slug
  %td.p-5= category.state
  %td.p-5= category.created_at
  %td.p-5= category.archived_at
  %td.p-5
    .flex.justify-center
      = link_to heroicon('pencil',
                         options: { class: 'mr-2 text-indigo-500 hover:text-indigo-800 transition-colors duration-300' }),
                edit_admin_category_path(category),
                data: { turbo_frame: '_top' }

      = link_to heroicon('trash',
                         options: { class: 'text-red-500 hover:text-red-800 transition-colors duration-300' }),
                admin_category_path(category),
                data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }

app/views/admin/categories/_form.html.haml
= form_with(model: [:admin, @category], class: 'max-w-2xl mx-auto') do |form|
  - if @category.errors.any?
    %div{style: "color: red"}
      %h2
        = pluralize(@category.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @category.errors.each do |error|
          %li= error.full_message

  .my-4
    %label= form.label :title, class: 'block mb-2 text-gray-600 text-sm tracking-wide'
    = form.text_field :title,
                      class: 'bg-gray-50 border-gray-300 text-gray-800 block w-full p-2 focus:border-indigo-700'

  .my-4
    %label= form.label :description, class: 'block mb-2 text-gray-600 text-sm tracking-wide'
    = form.text_area :description,
                     class: 'bg-gray-50 border-gray-300 text-gray-800 block w-full p-2 focus:border-indigo-700'

  .grid.grid-cols-2.gap-2
    %div
      = form.submit(@category.new_record? ? 'Save' : 'Update',
                    class: 'block text-gray-50 bg-indigo-500 hover:bg-indigo-800 w-full p-2 transition-colors duration-300 text-center tracking-wide')

    %div
      = link_to 'Back', admin_categories_path,
                class: 'block text-gray-50 bg-gray-500 hover:bg-gray-800 w-full p-2 transition-colors duration-300 text-center tracking-wide'

app/views/admin/categories/edit.html.haml
= provide :page_title, 'Edit category'

= render 'form'

app/views/admin/categories/index.html.haml
= provide :page_title, 'Categories'

.grid.grid-cols-15_85.h-full
  = render 'admin/shared/aside'

  .m-10
    %nav.mb-10
      %ul.flex.md:flex-row.justify-between
        %li
          = link_to 'New Category', new_admin_category_path,
                    class: 'block text-gray-50 bg-indigo-500 hover:bg-indigo-800 p-2 transition-colors duration-300 text-center tracking-wide'

        %li
          = search_form_for([:admin, @query], html: { 'data-turbo-frame': 'categories' }) do |form|
            = form.search_field :title_or_slug_i_cont,
                                placeholder: 'Searching by title or slug',
                                class: 'bg-gray-50 border-gray-300 text-gray-800 p-2 focus:border-indigo-700'
            = form.submit(class: 'text-gray-50 bg-indigo-500 hover:bg-indigo-800 p-2 transition-colors duration-300 text-center tracking-wide')

    %section
      = turbo_frame_tag 'categories' do
        %p.content-loading TODO: Table skeleton

        %table.border-collapse.w-full.leading-normal
          %thead.uppercase.border-b.border-indigo-500
            %tr
              %th.px-5.py-3.text-indigo-800.text-left= sort_link(@query, :title, 'Title')
              %th.px-5.py-3.text-indigo-800.text-left= sort_link(@query, :slug, 'Slug')
              %th.px-5.py-3.text-indigo-800.text-left= sort_link(@query, :state, 'State')
              %th.px-5.py-3.text-indigo-800.text-left= sort_link(@query, :created_at, 'Created at')
              %th.px-5.py-3.text-indigo-800.text-left= sort_link(@query, :archived_at, 'Archived at')
              %th.px-5.py-3.text-indigo-800 Actions
          %tbody
            = render @categories

app/views/admin/categories/new.html.haml
= provide :page_title, 'New category'

= render 'form'