config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  # TODO auth security https://thoughtbot.com/blog/rails-advanced-routing-constraints
  mount Sidekiq::Web => "/sidekiq"

  namespace :admin do
    root "home#index"

    resources :categories, except: :show
    resources :courses, except: %i[new create]
    resources :roles, shallow: true do
      resources :permissions, only: %i[create update] do
        patch :toggle, on: :member # move to toggle controller
      end
    end

    resources :documents, shallow: true, except: %i[new create] do
      resources :paragraphs, except: %i[index show]
    end

    resources :posts, except: %i[new create]
    resources :decks, except: %i[new create]
  end

  namespace :dashboard do
    root "home#index"

    resources :documents do
      resources :paragraphs, shallow: true, except: %i[index show]
    end

    resources :courses do
      resources :chapters, shallow: true, except: %i[index show]
    end

    resources :decks do
      resources :cards, shallow: true, except: %i[index show]
    end

    resources :class_rooms
    resources :posts
  end

  resources :categories, only: %i[index show]
  resources :posts, only: %i[index show]

  resource :registration, only: %i[new create]
  resource :session, only: %i[new create destroy]
  resource :password, only: %i[edit update]
  resource :remind_password, only: %i[new create]
  resource :reset_password, only: %i[edit update]

  get "main", to: "pages#main"
  get "about_us", to: "pages#about_us"
  get "terms_of_service", to: "pages#terms_of_service"
  get "services", to: "pages#services"

  get "up", to: "rails/health#show", as: :rails_health_check

  root "pages#main"
end

app/controllers/reset_passwords_controller.rb
# frozen_string_literal: true

class ResetPasswordsController < ApplicationController
  def edit
    @reset_password_form = User::ResetPasswordForm.new
  end

  def update
    @reset_password_form = User::ResetPasswordForm.new(reset_password_params.merge(token: token_params))

    if @reset_password_form.valid?
      user = @reset_password_form.user
      user.update(reset_password_params)
      redirect_to(new_session_path)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def token_params
    params.require(:token)
  end

  def reset_password_params
    params.require(:user_reset_password_form).permit(:password, :password_confirmation)
  end
end

app/views/reset_passwords/_form.html.haml
= provide :page_title, 'Reset your password'

= form_with(model: @reset_password_form, url: reset_password_path(token: params[:token]), method: :put,  class: 'max-w-xl border border-gray-300 p-10 mx-auto') do |form|
  - if form.object.errors.any?
    - form.object.errors.full_messages.each do |message|
      %div= message

  .my-4
    %label= form.label :password, 'New Password', class: 'block mb-2 text-gray-600 text-sm tracking-wide'
    = form.password_field :password, required: true,
                                     class: 'bg-gray-50 border-gray-300 text-gray-800 block w-full p-2 focus:border-indigo-700'

  .my-4
    %label= form.label :password_confirmation, class: 'block mb-2 text-gray-600 text-sm tracking-wide'
    = form.password_field :password_confirmation, required: true,
                                                  class: 'bg-gray-50 border-gray-300 text-gray-800 block w-full p-2 focus:border-indigo-700'

  %div
    = form.submit('Reset Password',
                  class: 'block text-gray-50 bg-indigo-500 hover:bg-indigo-800 w-full p-2 transition-colors duration-300 text-center tracking-wide')

app/views/reset_passwords/edit.html.haml
= provide :page_title, 'Remind Password'
= render 'form'